### ISSUE TITLE
push notifications when the application is not running

### ISSUE THREAD

**Issue by dinerozz** [mindbox-cloud/flutter-sdk#121]
Hello!
How can i solve the problem with sending push notifications when the application is not running (android)

**Comment by enotniy** [comment]
Hello @dinerozz,

To solve the problem with sending push notifications when the application is not running (on Android), please make sure that you call the Mindbox.initPushServices method in the native part of your Flutter application, specifically in the onCreate method of your Application class.

You can refer to the example provided in the Mindbox Flutter SDK repository. Here is a direct link to the relevant code snippet: [Example Code](https://github.com/mindbox-cloud/flutter-sdk/blob/aafe890bfbf3635e3621135a6511ffc8e38164f9/example/flutter_example/android/app/src/main/kotlin/cloud/mindbox/flutter_example/MainApplication.kt#L23).

Make sure you have this setup correctly in your Application class. This should help ensure that push notifications are handled even when your app is not running.

**Comment by dinerozz** [comment]
Yes, I am calling init Push Services. 
Notifications are displayed correctly when the application is running/minimized. However, if i swipe it from the task manager, notifications stop coming. 

Here is my code:

MainActivity:
`class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Mindbox.initPushServices(applicationContext, listOf(MindboxFirebase))
    }
}`

MindboxFirebaseMessagingService:
`class MindboxFirebaseMessagingService: FirebaseMessagingService()  {
    override fun onNewToken(token: String) {
        Mindbox.updatePushToken(applicationContext, token, MindboxFirebase)
        super.onNewToken(token)
    }

    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        super.onMessageReceived(remoteMessage)
        val channelId = "android_app_channel"
        val channelName = "Push notifications"
        val channelDescription = "Marketing Push notifications"
        val pushSmallIcon = R.drawable.ic_notification

        val messageWasHandled = Mindbox.handleRemoteMessage(
            context = applicationContext,
            message = remoteMessage,
            activities = mapOf(),
            channelId = channelId,
            channelName = channelName,
            pushSmallIcon = pushSmallIcon,
            defaultActivity = MainActivity::class.java,
            channelDescription = channelDescription
        )
        if (!messageWasHandled) {
            println("Message was not handled by Mindbox")
        }
    }
}`

AndroidManifest.xml:
`        <service android:name=".MindboxFirebaseMessagingService" android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>
`

**Comment by dinerozz** [comment]
@enotniy, do I need to add MainApplication.kt as in the example?

**Comment by enotniy** [comment]
> @enotniy, do I need to add MainApplication.kt as in the example?

Yes, you definitely need to call Mindbox.initPushServices in the onCreate method of your Application class. This is essential for ensuring that push notifications are handled properly even when your app is not running.

Additionally, don't forget to add your MainApplication to your AndroidManifest.xml file. You can refer to this example for guidance: [AndroidManifest.xml](https://github.com/mindbox-cloud/flutter-sdk/blob/develop/example/flutter_example/android/app/src/main/AndroidManifest.xml#L6).

**Comment by dinerozz** [comment]
Thanks a lot, it worked
