### ISSUE TITLE
problem with onPushClickReceived 

### ISSUE THREAD

**Issue by dinerozz** [mindbox-cloud/flutter-sdk#128]
Добрый день.  При клике на пуш возникает проблема с обработкой этого клика, в LogCat падает 410 ошибка
 error:  NetworkUtility.shouldRetryException: Unexpected response code 410 for https://api.mindbox.ru/mobile-push/delivered/.....

Также не всегда отрабатывает навигация по клику на пуш

**Comment by sergeysozinov** [comment]
Добрый день! 
410 ошибка это не проблема, этот запрос не используется. 
В [последней версии](https://github.com/mindbox-cloud/flutter-sdk/releases/tag/mindbox-v2.11.0) sdk мы в целом убрали этот запрос. 
Если навигация не работает при клике в выгруженное приложение, то обновитесь на последнюю версию, там эта проблема исправлена

**Comment by sergeysozinov** [comment]
@dinerozz вам помогло обновление sdk?

**Comment by dinerozz** [comment]
@sergeysozinov ошибки больше нет, с навигацией по прежнему проблемы (в режиме отладки). на реальном устройстве все нормально

**Comment by sergeysozinov** [comment]
Давайте логи посмотрим, чтобы понять, что не так идет в режиме отладки. Если вам удобно, напишите в тг @sergsozinov , кажется, что так побыстрее будет

**Comment by dinerozz** [comment]
Связались в tg, проблему решили, спасибо, закрываю тикет
