### ISSUE TITLE
iOS build fails for simulator

### ISSUE THREAD

**Issue by jacobsofteng** [mindbox-cloud/flutter-sdk#133]
Здравствуйте! Я работаю над интеграцией Mindbox SDK во flutter приложение. По части Android все работает прекрасно. Но есть проблемы по части iOS при добавлении rich-пушей. Я выполнил все шаги согласно документации. На физическом устройстве все работает. Но вот когда я пытаюсь запустить приложение на симуляторе, то получаю следующую ошибку:

Swift Compiler Error (Xcode): Header 'MindboxNotifications-Swift.h' not found /Users/mukhamedovyokubjon/Flutter/mobileapp/apps/client/build/ios/Debug-qa-iphonesimulator/MindboxNotifications/MindboxNotifications.framework/Modules/module.modulemap:8:9 

Swift Compiler Error (Xcode): Could not build Objective-C module 'MindboxNotifications' /Users/mukhamedovyokubjon/Flutter/mobileapp/apps/client/ios/MindboxNotificationServiceExtension/NotificationService.swift:8:7

Header класс не генерится при сборке приложения на ios симуляторе

**Comment by justSmK** [comment]
Добрый день. 
Попробуйте пожалуйста запустить у себя [Example приложения с нашим SDK](https://github.com/mindbox-cloud/flutter-sdk/tree/develop/example/flutter_example).
Если Example запустится нормально, пуши будут отрабатывать корректно, то нужно будет перепроверить корректность интеграции в основном приложении.
Если нет, значит вероятнее всего проблема с окружением и нужно будет изучать уже её.

**Comment by jacobsofteng** [comment]
> Добрый день. Попробуйте пожалуйста запустить у себя [Example приложения с нашим SDK](https://github.com/mindbox-cloud/flutter-sdk/tree/develop/example/flutter_example). Если Example запустится нормально, пуши будут отрабатывать корректно, то нужно будет перепроверить корректность интеграции в основном приложении. Если нет, значит вероятнее всего проблема с окружением и нужно будет изучать уже её.

Example приложение запустилось в симуляторе, работает исправно. Я просто не знаю почему такое странное поведение наблюдается в основном приложении. Именно на симуляторе билд фейлится

**Comment by justSmK** [comment]
> > Добрый день. Попробуйте пожалуйста запустить у себя [Example приложения с нашим SDK](https://github.com/mindbox-cloud/flutter-sdk/tree/develop/example/flutter_example). Если Example запустится нормально, пуши будут отрабатывать корректно, то нужно будет перепроверить корректность интеграции в основном приложении. Если нет, значит вероятнее всего проблема с окружением и нужно будет изучать уже её.
> 
> Example приложение запустилось в симуляторе, работает исправно. Я просто не знаю почему такое странное поведение наблюдается в основном приложении. Именно на симуляторе билд фейлится

У нашей команды не получилось воспроизвести данную проблему. `podfile` и `build_settings` не содержат каких-либо дополнительных условий, которые могли бы как-то повлиять на `header` файлы. Пока я могу только порекомендовать попробовать переинтегрироваться, предварительно очистив Derived Data в Xcode и удалив папку Pods из проекта. Возможно стоит сначала попробовать просто переустановить сами Pods, удалив их из директории проекта и произвести установку заново, также почистив кэш самого flutter.
