### ISSUE TITLE
Kotlin Gradle plugin version

### ISSUE THREAD

**Issue by vmeretin** [mindbox-cloud/flutter-sdk#49]
```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':mindbox_android' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

It reproduces after updating Android Gradle plugin to version 7.3.0

**Comment by RedFox64** [comment]
I have the same problem

**Comment by enotniy** [comment]
Bump kotlin-gradle-plugin version to 7.4.2 in 2.8.0 release. See [CHANGELOG for android](https://github.com/mindbox-cloud/flutter-sdk/blob/master/mindbox_android/CHANGELOG.md)
