### ISSUE TITLE
await for MindboxPlatform.instance.init

### ISSUE THREAD

**Issue by AntonovAleksandr** [mindbox-cloud/flutter-sdk#61]
https://github.com/mindbox-cloud/flutter-sdk/blob/609551e7e3792f22190b9c386e1e35bf0d582dec/mindbox/lib/mindbox.dart#L57-L60

Не хватает await при вызове метода init, из-за этого скрывается Future и нарушается порядок инициализации

**Comment by AntonovAleksandr** [comment]
Проблема актуальна для release/2.8.0

**Comment by Vailence** [comment]
Закрываем потому что это так и должно работать.
