### ISSUE TITLE
App build always failed

### ISSUE THREAD

**Issue by dronn1kDev** [mindbox-cloud/flutter-sdk#74]
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:checkProdDebugAarMetadata'.
Could not resolve all files for configuration ':app:prodDebugRuntimeClasspath'.
Could not find com.huawei.hms:push:6.5.0.300.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/com/huawei/hms/push/6.5.0.300/push-6.5.0.300.pom
- https://repo.maven.apache.org/maven2/com/huawei/hms/push/6.5.0.300/push-6.5.0.300.pom
- https://storage.googleapis.com/download.flutter.io/com/huawei/hms/push/6.5.0.300/push-6.5.0.300.pom
- https://jcenter.bintray.com/com/huawei/hms/push/6.5.0.300/push-6.5.0.300.pom
Required by:
project :app > project :mindbox_android > cloud.mindbox:mindbox-huawei:2.8.4
Could not find com.huawei.hms:ads-identifier:3.4.39.302.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/com/huawei/hms/ads-identifier/3.4.39.302/ads-identifier-3.4.39.302.pom
- https://repo.maven.apache.org/maven2/com/huawei/hms/ads-identifier/3.4.39.302/ads-identifier-3.4.39.302.pom
- https://storage.googleapis.com/download.flutter.io/com/huawei/hms/ads-identifier/3.4.39.302/ads-identifier-3.4.39.302.pom
- https://jcenter.bintray.com/com/huawei/hms/ads-identifier/3.4.39.302/ads-identifier-3.4.39.302.pom
Required by:
project :app > project :mindbox_android > cloud.mindbox:mindbox-huawei:2.8.4

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

Get more help at https://help.gradle.org/
BUILD FAILED in 19s

Flutter doctor output:
[✓] Flutter (Channel stable, 3.7.12, on macOS 14.4 23E214 darwin-arm64, locale en-MD)
• Flutter version 3.7.12 on channel stable at /Users/dronn1k/flutter/sdk/3.7.12
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 4d9e56e694 (11 months ago), 2023-04-17 21:47:46 -0400
• Engine revision 1a65d409c7
• Dart version 2.19.6
• DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
• Android SDK at /Users/dronn1k/Library/Android/sdk
• Platform android-34, build-tools 34.0.0
• Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java
• Java version Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 15E204a
• CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (version 2023.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
✗ Unable to find bundled Java version.
• Try updating or re-installing Android Studio.

[✓] VS Code (version 1.87.2)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.84.0

[✓] Connected device (2 available)
• sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 12 (API 31) (emulator)
• macOS (desktop) • macos • darwin-arm64 • macOS 14.4 23E214 darwin-arm64

[✓] HTTP Host Availability
• All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by enotniy** [comment]
@dronn1kDev We're planning to fix this in the upcoming release. In the meantime, you can use the following code in your `android/app/build.gradle` to address this problem:
```
configurations.all {
    exclude group: 'cloud.mindbox', module: 'mindbox-huawei'
}
```
Please let us know if you encounter any further issues.

**Comment by dronn1kDev** [comment]
@enotniy Thank you for the reply!
It works. My app is buildable now.

**Comment by yom-ko** [comment]
> @dronn1kDev We're planning to fix this in the upcoming release. In the meantime, you can use the following code in your `android/app/build.gradle` to address this problem:
> 
> ```
> configurations.all {
>     exclude group: 'cloud.mindbox', module: 'mindbox-huawei'
> }
> ```

@enotniy I've the same or similar issue probably, but adding the snippet doesn't seem to help. Am I missing something?

![CleanShot 2024-04-05 at 15 38 10@2x](https://github.com/mindbox-cloud/flutter-sdk/assets/2071596/cdd717e2-b035-4df5-9ad0-c660b53c3210)

**Comment by enotniy** [comment]
@yom-ko Could you try implement version 2.8.5 ? 
<img width="465" alt="Screenshot 2024-04-05 at 17 50 35" src="https://github.com/mindbox-cloud/flutter-sdk/assets/13769083/e33d09f5-5c1a-430a-8f45-19728be7bc5c">

**Comment by yom-ko** [comment]
> @yom-ko Could you try implement version 2.8.5 ? 
> <img width="465" alt="Screenshot 2024-04-05 at 17 50 35" src="https://github.com/mindbox-cloud/flutter-sdk/assets/13769083/e33d09f5-5c1a-430a-8f45-19728be7bc5c">
> 

Yep, I guess the issue is gone with 2.8.5. Can't be 💯 sure for now because I still cannot build the app. But this time the error is different and not related to Mindbox, apparently. Thanks for the help!
