### ISSUE TITLE
Method 'updateNotificationPermissionStatus' isn't work

### ISSUE THREAD

**Issue by Bondidos** [mindbox-cloud/flutter-sdk#75]
In file 
lib/src/types/mindbox_mock_method_call_handler.dart
method updateNotificationPermissionStatus

The problem is the flag 'granted' do not passed into native part as argument 

![image](https://github.com/mindbox-cloud/flutter-sdk/assets/69970266/a05ff011-8d37-48be-8f77-175465e8a2a9)

How reproduce

1. IOS Appdelegate extends FlutterAppDelegate. According with instructions
https://developers.mindbox.ru/docs/ios-send-push-notifications-appdelegate
2. I need to ask permission a little bit later, than on start of my app, so I commented this part of code
![image](https://github.com/mindbox-cloud/flutter-sdk/assets/69970266/fa9dc2f0-1eea-4d7c-8c33-28e22554f766)
3. Next I use method 'updateNotificationPermissionStatus' like in instructions (ask permission and send)
https://developers.mindbox.ru/docs/методы-flutter-sdk#updatenotificationpermissionstatus-since-283
4. As result, user's card do not have updated status (permission) and push cannot be sent.

Locally I fixed this issue by passing argument and all works fine

**Comment by enotniy** [comment]
Fixed in [release v2.8.4](https://github.com/mindbox-cloud/flutter-sdk/releases/tag/mindbox-v2.8.4)
